# The URL the site will be built for
base_url = "https://stuff.kori.wtf"
compile_sass = true
theme = "even"
highlight_code = false
build_search_index = false

title = "Kori"
description = ""
generate_categories_pages = true
generate_tags_pages = true

[extra]
# Put all your custom variables here
even_menu = [
    { url = "$BASE_URL", name = "Home" }
]
even_title = "Kori"
